import "./styles.css"
import "./w3.css"
import "./confirmation.css"
import "./codeverification.css"

import "./createinvoice.css"
import "./editinvoice.css"
import "./reviewinvoice.css"
import "./invoicesent.css"

import "./paymenthistory.css"
import "./activities.css"
import "./myinvoice.css"
import "./invoicehistory.css"
import "./clients.css"
import "./payouts.css"
import "./shareinvoice.css"
import "./profile.css"
import "./settings.css"
